## Download specific versions and source code locally

In [1]:
# torch==1.10.2
!pip install transformers==4.16.2 datasets==1.17.0 tokenizers==0.11.6 wandb==0.12.14

     |████████████████████████████████| 3.5 MB 5.5 MB/s 
     |████████████████████████████████| 306 kB 52.5 MB/s 
     |████████████████████████████████| 6.5 MB 34.9 MB/s 
     |████████████████████████████████| 1.8 MB 36.0 MB/s 
     |████████████████████████████████| 77 kB 6.2 MB/s 
     |████████████████████████████████| 596 kB 37.4 MB/s 
     |████████████████████████████████| 895 kB 36.8 MB/s 
     |████████████████████████████████| 136 kB 51.8 MB/s 
     |████████████████████████████████| 212 kB 50.8 MB/s 
     |████████████████████████████████| 1.1 MB 45.1 MB/s 
     |████████████████████████████████| 144 kB 45.0 MB/s 
     |████████████████████████████████| 181 kB 51.0 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
     |████████████████████████████████| 144 kB 51.3 MB/s 
     |████████████████████████████████| 271 kB 45.9 MB/s 
     |████████████████████████████████| 94 kB 3.2 MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8

In [1]:
!nvidia-smi

Mon Apr 11 15:54:23 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P0    76W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
%cd /content
!rm -r ntu_nlp_al
!git clone -b kretov/adding_tagging https://github.com/DevKretov/ntu_nlp_al

/content
Cloning into 'ntu_nlp_al'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 131 (delta 68), reused 99 (delta 41), pack-reused 0
Receiving objects: 100% (131/131), 56.54 MiB | 11.72 MiB/s, done.
Resolving deltas: 100% (68/68), done.
Checking out files: 100% (24/24), done.


In [4]:

%cd ntu_nlp_al/

/content/ntu_nlp_al


## Initialisation

In [5]:
import torch
from transformers import get_scheduler
from datasets import list_metrics, load_metric

from active_learning_trainer import ALTrainer
from transformers import AutoTokenizer
from dataset import Dataset, TokenClassificationDataset
from model import Model


import datetime
import wandb


2022-04-11 15:54:40,780 git.cmd DEBUG:Popen(['git', 'version'], cwd=/content/ntu_nlp_al, universal_newlines=False, shell=None, istream=None)
2022-04-11 15:54:40,808 git.cmd DEBUG:Popen(['git', 'version'], cwd=/content/ntu_nlp_al, universal_newlines=False, shell=None, istream=None)
2022-04-11 15:54:41,174 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:54:41,331 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /bert-base-multilingual-uncased/resolve/main/config.json HTTP/1.1" 200 0


In [6]:
parameters = dict()
parameters['use_gpu'] = True

parameters['weights_and_biases_on'] = True
parameters['weights_and_biases_key'] = '5e5e00356042a33b5cb271399b8d05c9c9d6ded8'
# TODO: run name based on timestamp
current_timestamp = str(datetime.datetime.now()).split('.')[0]

# TODO: implement it
parameters['weights_and_biases_save_predictions'] = False

parameters['pretrained_model_name'] = 'prajjwal1/bert-small' #'distilbert-base-uncased'


# parameters['train_dataset_file_path'] = 'data/imdb/train_IMDB.csv'
# parameters['val_dataset_file_path'] = 'data/imdb/test_IMDB.csv'
# parameters['test_dataset_file_path'] = 'data/imdb/test_IMDB.csv'

parameters['dataset_from_datasets_hub'] = False
parameters['dataset_from_datasets_hub_name'] = 'conll2003'
parameters['train_dataset_file_path'] = 'data/news/train.csv'
parameters['val_dataset_file_path'] = 'data/news/val.csv'
parameters['test_dataset_file_path'] = 'data/news/test.csv'
parameters['dataset_file_delimiter'] = ','

### FIRST IS FOR TAGGING
parameters['dataset_text_column_name'] =  'tokens' #'text'
parameters['dataset_label_column_name'] = 'ner_tags'#'airline_sentiment'

### THIS IS FOR CLASSIFICATION
### FIRST OF ALL, LOOK AT COLUMNS IN DATASET CSV!!! THEN WRITE HERE!
parameters['dataset_text_column_name'] = 'text_cleaned'  # 'text'
parameters['dataset_label_column_name'] = 'label_reduced'  # 'airline_sentiment'

# TODO: implement this with CrossEntropyLoss
parameters['loss'] = 'cross_entropy'
parameters['loss_weighted'] = False

parameters['class_imbalance_reweight'] = True
parameters['train_batch_size'] = 32
parameters['val_batch_size'] = 64
parameters['test_batch_size'] = 64
parameters['epochs'] = 5
# parameters['finetuned_model_type'] = 'classification'
parameters['finetuned_model_type'] = 'classification'
model_type = parameters['finetuned_model_type']


parameters['al_iterations'] = 100
parameters['init_dataset_size'] = 32
parameters['add_dataset_size'] = 32
### HERE CAN BE least_confidence OR badge OR random OR kmeans OR entropy
parameters['al_strategy'] = 'kmeans' #'least_confidence'
# IF YOU WANT TO TRAIN ON THE WHOLE MODEL
parameters['full_train'] = False

parameters['debug'] = False

In [7]:
device = 'cpu'
if parameters['use_gpu']:
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

parameters['weights_and_biases_run_name'] = f'{current_timestamp}_run_{model_type}_{device}'
print(f'Device set to {device}!')

Device set to cuda:0!


## Preparing tokenizer, dataset, model

In [8]:
tokenizer = AutoTokenizer.from_pretrained(parameters['pretrained_model_name'])

dataset_obj = None
if parameters['finetuned_model_type'] == 'classification':
    dataset_obj = Dataset(tokenizer)
elif parameters['finetuned_model_type'] == 'tagging':
    dataset_obj = TokenClassificationDataset(tokenizer)
else:
    model_type = parameters['finetuned_model_type']
    raise NotImplementedError(f'Type {model_type} not supported yet!')

2022-04-11 15:54:41,652 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:54:41,787 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/tokenizer_config.json HTTP/1.1" 404 0
2022-04-11 15:54:41,795 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:54:41,936 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/config.json HTTP/1.1" 200 0
2022-04-11 15:54:41,981 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:54:42,114 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/tokenizer_config.json HTTP/1.1" 404 0
2022-04-11 15:54:42,122 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:54:42,256 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-sma

In [9]:
if parameters['dataset_from_datasets_hub']:
    dataset_name = parameters['dataset_from_datasets_hub_name']
    dataset_obj.load_hosted_dataset(dataset_name)
else:
    data_files = {
        'train': [parameters['train_dataset_file_path']],
        'val': [parameters['val_dataset_file_path']],
        'test': [parameters['test_dataset_file_path']]
    }

    dataset_obj.load_csv_dataset(
        data_files,
        delimiter=parameters['dataset_file_delimiter']
    )

dataset_obj.truncate_dataset('train', 10000)
dataset_obj.truncate_dataset('val', 1000)
dataset_obj.truncate_dataset('test', 10000)

dataset_obj.prepare_dataset(parameters['dataset_label_column_name'], parameters['dataset_text_column_name'], )
# dataset_obj.prepare_labels(parameters['dataset_label_column_name'])
# dataset_obj.encode_dataset(parameters['dataset_text_column_name'])

print(f'Categories: {dataset_obj.get_all_categories()}')
num_labels = dataset_obj.get_num_categories()

2022-04-11 15:54:43,297 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): s3.amazonaws.com:443
2022-04-11 15:54:43,510 urllib3.connectionpool DEBUG:https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/datasets/csv/csv.py HTTP/1.1" 200 0
2022-04-11 15:54:43,521 datasets.builder WARNING:Using custom data configuration default-282ea53093e4eac7


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-282ea53093e4eac7/0.0.0/6b9057d9e23d9d8a2f05b985917a0da84d70c5dae3d22ddd8a3f22fb01c69d9e. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

Flattening the indices:   0%|          | 0/10 [00:00<?, ?ba/s]

Casting to class labels:   0%|          | 0/10 [00:00<?, ?ba/s]

Casting the dataset:   0%|          | 0/1 [00:00<?, ?ba/s]

Flattening the indices:   0%|          | 0/1 [00:00<?, ?ba/s]

Casting to class labels:   0%|          | 0/1 [00:00<?, ?ba/s]

Casting the dataset:   0%|          | 0/1 [00:00<?, ?ba/s]

Casting to class labels:   0%|          | 0/3 [00:00<?, ?ba/s]

Casting the dataset:   0%|          | 0/1 [00:00<?, ?ba/s]

  0%|          | 0/10000 [00:00<?, ?ex/s]

  0%|          | 0/1000 [00:00<?, ?ex/s]

  0%|          | 0/2808 [00:00<?, ?ex/s]

  0%|          | 0/10 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

  0%|          | 0/3 [00:00<?, ?ba/s]

Categories: {'alt': 0, 'comp': 1, 'misc': 2, 'rec': 3, 'sci': 4, 'soc': 5, 'talk': 6}


In [10]:
model = Model(
        parameters['pretrained_model_name'],
        model_type=parameters['finetuned_model_type'],
        num_labels=num_labels
    )

2022-04-11 15:55:00,184 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:55:00,322 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/config.json HTTP/1.1" 200 0
2022-04-11 15:55:00,332 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:55:00,465 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/pytorch_model.bin HTTP/1.1" 302 0
Some weights of the model checkpoint at prajjwal1/bert-small were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initi

### Connect to W&B environment

In [11]:
if parameters['weights_and_biases_on']:
    wandb.login(key='5e5e00356042a33b5cb271399b8d05c9c9d6ded8')
    wandb.init(
        name=parameters['weights_and_biases_run_name'],
        project='ntu_al',
        reinit=True
    )

    wandb.config.update(parameters)
    wandb.watch(model.model)

2022-04-11 15:55:06,161 urllib3.connectionpool DEBUG:Starting new HTTP connection (1): 172.28.0.2:9000
2022-04-11 15:55:06,169 urllib3.connectionpool DEBUG:http://172.28.0.2:9000 "GET /api/sessions?token= HTTP/1.1" 200 420
2022-04-11 15:55:06,187 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): api.wandb.ai:443
2022-04-11 15:55:06,307 urllib3.connectionpool DEBUG:https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2022-04-11 15:55:06,316 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): api.wandb.ai:443
2022-04-11 15:55:06,372 urllib3.connectionpool DEBUG:https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
wandb: Currently logged in as: kretov (use `wandb login --relogin` to force relogin)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai t

### Init trainer and combine everything

In [12]:
trainer = ALTrainer(
    wandb_on=parameters['weights_and_biases_on'],
    imbalanced_training=parameters['class_imbalance_reweight'],
    model_type=parameters['finetuned_model_type']
)
trainer.set_model(model)

# TODO: add strategy
trainer.set_strategy(None)
trainer.set_dataset(dataset_obj)
dataset_obj.prepare_dataloaders(
    train_batch_size=parameters['train_batch_size'],
    val_batch_size=parameters['val_batch_size'],
    test_batch_size=parameters['test_batch_size'],
)

optimizer = torch.optim.AdamW(model.model.parameters(), lr=5e-5)
trainer.set_optimizer(optimizer)

num_training_steps = parameters['epochs'] * trainer.get_training_steps_num()

lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)
trainer.set_lr_scheduler(lr_scheduler)
trainer.set_device(device)

trainer.add_evaluation_metric(load_metric('accuracy'))

if parameters['finetuned_model_type'] == 'tagging':
    trainer.add_evaluation_metric(load_metric('seqeval'))
else:
    trainer.add_evaluation_metric(load_metric('f1'))
    trainer.add_evaluation_metric(load_metric('precision'))
    trainer.add_evaluation_metric(load_metric('recall'))

2022-04-11 15:55:15,478 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): s3.amazonaws.com:443
2022-04-11 15:55:15,643 urllib3.connectionpool DEBUG:https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/metrics/accuracy/accuracy.py HTTP/1.1" 200 0
2022-04-11 15:55:15,650 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): raw.githubusercontent.com:443
2022-04-11 15:55:15,698 urllib3.connectionpool DEBUG:https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.17.0/metrics/accuracy/accuracy.py HTTP/1.1" 200 0
2022-04-11 15:55:15,720 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): s3.amazonaws.com:443
2022-04-11 15:55:15,865 urllib3.connectionpool DEBUG:https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/metrics/f1/f1.py HTTP/1.1" 200 0
2022-04-11 15:55:15,870 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): raw.githubusercontent.com:443
2022-04-11 15:55:15,916 urllib3.connectionpool DEBUG:

## Train

In [ ]:
if parameters['full_train']:
    trainer.full_train(
        train_epochs=parameters['epochs'],
        train_batch_size=parameters['train_batch_size'],
        val_batch_size=parameters['val_batch_size'],
        test_batch_size=parameters['test_batch_size'],
        debug=parameters['debug']
    )

trainer.al_train(
    al_iterations=parameters['al_iterations'],
    init_dataset_size=parameters['init_dataset_size'],
    add_dataset_size=parameters['add_dataset_size'],
    train_epochs=parameters['epochs'],
    strategy=parameters['al_strategy'],
    train_batch_size=parameters['train_batch_size'],
    val_batch_size=parameters['val_batch_size'],
    test_batch_size=parameters['test_batch_size'],
    debug=parameters['debug']
)

2022-04-11 15:55:16,439 root INFO:Training initialized!


  0%|          | 0/10 [00:00<?, ?ba/s]

  0%|          | 0/32 [00:00<?, ?ex/s]

  0%|          | 0/10 [00:00<?, ?ba/s]

  0%|          | 0/9968 [00:00<?, ?ex/s]

2022-04-11 15:55:40,982 root DEBUG:AL train dataset length: 32, rest dataset length: 9968
2022-04-11 15:55:41,012 root INFO:Training is run on 1 batches!
2022-04-11 15:55:41,014 root INFO:Evaluation is run on 16 batches!
2022-04-11 15:55:41,015 root INFO:Testing is run on 44 batches!
2022-04-11 15:55:41,016 root INFO:

2022-04-11 15:55:41,019 root INFO:AL K Means strategy applied!
2022-04-11 15:55:41,020 root INFO:
2022-04-11 15:55:41,023 root INFO:
AL iteration   1/100
2022-04-11 15:55:41,028 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:55:41,189 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/config.json HTTP/1.1" 200 0
2022-04-11 15:55:41,199 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:55:41,339 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/pytorch_model.bin HTTP/1.1" 302 0
Some we

Training mean loss: 2.2104036808013916: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]

2022-04-11 15:55:45,407 root INFO:Epoch finished. Evaluation:
2022-04-11 15:55:45,410 root INFO:

Epoch   2


Training mean loss: 1.8220746517181396: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]

2022-04-11 15:55:46,066 root INFO:Epoch finished. Evaluation:
2022-04-11 15:55:46,072 root INFO:

Epoch   3


Training mean loss: 1.5997488498687744: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s]

2022-04-11 15:55:46,738 root INFO:Epoch finished. Evaluation:
2022-04-11 15:55:46,741 root INFO:

Epoch   4


Training mean loss: 1.5530273914337158: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]

2022-04-11 15:55:47,402 root INFO:Epoch finished. Evaluation:
2022-04-11 15:55:47,408 root INFO:

Epoch   5


Training mean loss: 1.5828036069869995: 100%|██████████| 1/1 [00:00<00:00,  1.50it/s]

2022-04-11 15:55:48,085 root INFO:Epoch finished. Evaluation:
2022-04-11 15:55:48,088 root DEBUG:Is model on CUDA - cuda:0
2022-04-11 15:55:48,089 root INFO:Running Eval mode...


Eval mean loss: 1.8112898841500282: 100%|██████████| 16/16 [00:07<00:00,  2.06it/s]

2022-04-11 15:55:55,864 root INFO:Test set evaluation:
2022-04-11 15:55:55,865 root DEBUG:Is model on CUDA - cuda:0
2022-04-11 15:55:55,870 root INFO:Running Test mode...



Test mean loss: 1.8108626956289464: 100%|██████████| 44/44 [00:21<00:00,  2.07it/s]

2022-04-11 15:56:17,270 root INFO:
Metrics, confusion matrix
2022-04-11 15:56:17,299 root INFO:[[  0  30   0   0   5  58  28]
 [  0 306   0   1 261 111  44]
 [  0  74   0   0  32  19   3]
 [  0 252   0   3  83 159 107]
 [  0 215   0   0 102 206  87]
 [  0  22   0   0   6  91  23]
 [  0 129   0   0  29 250  72]]
2022-04-11 15:56:17,312 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f8326e693d0>, 'accuracy': 0.2029936974789916}
2022-04-11 15:56:17,317 root WARNING:There is label not found in predictions: {'alt', 'misc'}
2022-04-11 15:56:17,323 root WARNING:Printing metric without this label
2022-04-11 15:56:17,342 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f8326e693d0>, 'accuracy': 0.2029936974789916, 'f1': 0.18272028245284463}
2022-04-11 15:56:17,347 root WARNING:There is label not found in predictions: {'alt', 'misc'}
2022-04-11 15:56:17,350 root WARNING:Printing metric without this label
2022-04-11 15:56:17,371 root INFO:{'conf_mat': <wandb.viz.CustomChart 


Training mean loss: 1.5828036069869995: 100%|██████████| 1/1 [00:30<00:00, 30.24s/it]

2022-04-11 15:56:17,664 root DEBUG:Model trained! Running AL strategy...
2022-04-11 15:56:17,682 root DEBUG:AL evaluation iteration



AL evaluation iteration. Batch   312/312: 100%|██████████| 312/312 [01:17<00:00,  4.01it/s]


2022-04-11 15:57:50,730 root DEBUG:Returned 32 indices from strategy
2022-04-11 15:57:50,734 root DEBUG:Before updating AL datasets: train size = 32, unlabelled size = 9968, sum: 10000 
2022-04-11 15:57:50,751 root DEBUG:Filtering...


  0%|          | 0/10 [00:00<?, ?ba/s]

2022-04-11 15:57:54,365 root DEBUG:Adding dataset_index column...


  0%|          | 0/9936 [00:00<?, ?ex/s]

2022-04-11 15:58:08,099 root DEBUG:Setting format...
2022-04-11 15:58:08,101 root DEBUG:Smth else...


  0%|          | 0/64 [00:00<?, ?ex/s]

2022-04-11 15:58:08,288 root DEBUG:
Updated AL datasets: train size = 64, unlabelled size = 9936, sum: 10000 
2022-04-11 15:58:08,310 root INFO:
2022-04-11 15:58:08,312 root INFO:
AL iteration   2/100
2022-04-11 15:58:08,317 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:58:08,482 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/config.json HTTP/1.1" 200 0
2022-04-11 15:58:08,493 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 15:58:08,631 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/pytorch_model.bin HTTP/1.1" 302 0
Some weights of the model checkpoint at prajjwal1/bert-small were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transfor

Training mean loss: 1.9161456227302551: 100%|██████████| 2/2 [00:01<00:00,  1.56it/s]

2022-04-11 15:58:10,700 root INFO:Epoch finished. Evaluation:
2022-04-11 15:58:10,704 root INFO:

Epoch   2


Training mean loss: 1.748725175857544: 100%|██████████| 2/2 [00:01<00:00,  1.55it/s]

2022-04-11 15:58:12,009 root INFO:Epoch finished. Evaluation:
2022-04-11 15:58:12,011 root INFO:

Epoch   3


Training mean loss: 1.630638837814331: 100%|██████████| 2/2 [00:01<00:00,  1.55it/s]

2022-04-11 15:58:13,326 root INFO:Epoch finished. Evaluation:
2022-04-11 15:58:13,332 root INFO:

Epoch   4


Training mean loss: 1.6749001741409302: 100%|██████████| 2/2 [00:01<00:00,  1.54it/s]

2022-04-11 15:58:14,638 root INFO:Epoch finished. Evaluation:
2022-04-11 15:58:14,642 root INFO:

Epoch   5


Training mean loss: 1.4264768958091736: 100%|██████████| 2/2 [00:01<00:00,  1.55it/s]

2022-04-11 15:58:15,945 root INFO:Epoch finished. Evaluation:
2022-04-11 15:58:15,950 root DEBUG:Is model on CUDA - cuda:0
2022-04-11 15:58:15,954 root INFO:Running Eval mode...


Eval mean loss: 1.6826567649841309: 100%|██████████| 16/16 [00:07<00:00,  2.10it/s]

2022-04-11 15:58:23,580 root INFO:Test set evaluation:
2022-04-11 15:58:23,585 root DEBUG:Is model on CUDA - cuda:0
2022-04-11 15:58:23,589 root INFO:Running Test mode...



Test mean loss: 1.6834015548229218: 100%|██████████| 44/44 [00:21<00:00,  2.08it/s]

2022-04-11 15:58:44,886 root INFO:
Metrics, confusion matrix
2022-04-11 15:58:44,910 root INFO:[[  4   1   0   0  21  46  49]
 [  5  34   0  23 636   3  22]
 [  0   8   0   6 104   2   8]
 [ 10   4   0 253 219   3 115]
 [  4  10   0  11 471  23  91]
 [  2   0   0   7  23  83  27]
 [ 11   3   1   7 111  66 281]]
2022-04-11 15:58:44,924 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f83200dc250>, 'accuracy': 0.3949579831932773}
2022-04-11 15:58:44,942 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f83200dc250>, 'accuracy': 0.3949579831932773, 'f1': 0.3441198115884949}
2022-04-11 15:58:44,969 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f83200dc250>, 'accuracy': 0.3949579831932773, 'f1': 0.3441198115884949, 'precision': 0.48796664375355775}
2022-04-11 15:58:45,003 root INFO:{'conf_mat': <wandb.viz.CustomChart object at 0x7f83200dc250>, 'accuracy': 0.3949579831932773, 'f1': 0.3441198115884949, 'precision': 0.48796664375355775, 'recall': 0.3949579831932


Training mean loss: 1.4264768958091736: 100%|██████████| 2/2 [00:30<00:00, 15.22s/it]

2022-04-11 15:58:45,101 root DEBUG:Model trained! Running AL strategy...
2022-04-11 15:58:45,116 root DEBUG:AL evaluation iteration



AL evaluation iteration. Batch   311/311: 100%|██████████| 311/311 [01:18<00:00,  3.94it/s]


2022-04-11 16:00:22,699 root DEBUG:Returned 32 indices from strategy
2022-04-11 16:00:22,702 root DEBUG:Before updating AL datasets: train size = 64, unlabelled size = 9936, sum: 10000 
2022-04-11 16:00:22,722 root DEBUG:Filtering...


  0%|          | 0/10 [00:00<?, ?ba/s]

2022-04-11 16:00:26,458 root DEBUG:Adding dataset_index column...


  0%|          | 0/9904 [00:00<?, ?ex/s]

2022-04-11 16:00:41,326 root DEBUG:Setting format...
2022-04-11 16:00:41,329 root DEBUG:Smth else...


  0%|          | 0/96 [00:00<?, ?ex/s]

2022-04-11 16:00:41,552 root DEBUG:
Updated AL datasets: train size = 96, unlabelled size = 9904, sum: 10000 
2022-04-11 16:00:41,578 root INFO:
2022-04-11 16:00:41,580 root INFO:
AL iteration   3/100
2022-04-11 16:00:41,585 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 16:00:41,741 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/config.json HTTP/1.1" 200 0
2022-04-11 16:00:41,750 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): huggingface.co:443
2022-04-11 16:00:41,897 urllib3.connectionpool DEBUG:https://huggingface.co:443 "HEAD /prajjwal1/bert-small/resolve/main/pytorch_model.bin HTTP/1.1" 302 0
Some weights of the model checkpoint at prajjwal1/bert-small were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transfor

Training mean loss: 1.8519086043039958: 100%|██████████| 3/3 [00:01<00:00,  1.56it/s]

2022-04-11 16:00:44,573 root INFO:Epoch finished. Evaluation:
2022-04-11 16:00:44,577 root INFO:

Epoch   2


Training mean loss: 1.732120951016744: 100%|██████████| 3/3 [00:01<00:00,  1.54it/s]

2022-04-11 16:00:46,537 root INFO:Epoch finished. Evaluation:
2022-04-11 16:00:46,541 root INFO:

Epoch   3


Training mean loss: 1.582826852798462: 100%|██████████| 3/3 [00:01<00:00,  1.56it/s]

2022-04-11 16:00:48,485 root INFO:Epoch finished. Evaluation:
2022-04-11 16:00:48,488 root INFO:

Epoch   4


Training mean loss: 1.4324580033620198: 100%|██████████| 3/3 [00:02<00:00,  1.47it/s]

2022-04-11 16:00:50,546 root INFO:Epoch finished. Evaluation:
2022-04-11 16:00:50,554 root INFO:

Epoch   5


Training mean loss: 1.267296592394511: 100%|██████████| 3/3 [00:01<00:00,  1.52it/s]

2022-04-11 16:00:52,545 root INFO:Epoch finished. Evaluation:
2022-04-11 16:00:52,548 root DEBUG:Is model on CUDA - cuda:0
2022-04-11 16:00:52,550 root INFO:Running Eval mode...


  0%|          | 0/16 [00:00<?, ?it/s]